### ISSUE TITLE
b站来的

### ISSUE THREAD

**Issue by 2439905184** [Quandong-Zhang/movie2galagame#2]
好奇 先start一下
是ren py做游戏运行runtime 是吧

**Comment by Quandong-Zhang** [comment]
不太清楚你的意思。
用法是运行main.py生成renpy脚本，再用renpy运行rpy脚本文件。

**Comment by Quandong-Zhang** [comment]
runtime是指文件吗，
跟那个应该没关系..............

**Comment by 2439905184** [comment]
runtime 就是运行环境的意思。比如说java依赖jre虚拟机运行环境 这个就是一个runtime 。我是这么理解的

**Comment by 2439905184** [comment]
把renpy作为游戏的运行环境。

**Comment by 2439905184** [comment]
我在学习renpy，国内bke引擎的语法太啰嗦了。

**Comment by Quandong-Zhang** [comment]
那基本是这样，
这个项目的原理就是用python脚本处理srt和MP4文件生成游戏脚本，再用renpy渲染。

**Comment by Quandong-Zhang** [comment]
> 我在学习renpy，国内bke引擎的语法太啰嗦了。
是，renpy的语法是最简单的。
